# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ethos/elint/services/product/identity/account_assistant/action_account_assistant.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ethos.elint.entities import account_pb2 as ethos_dot_elint_dot_entities_dot_account__pb2
try:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_account__pb2.google_dot_protobuf_dot_timestamp__pb2
except AttributeError:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_account__pb2.google.protobuf.timestamp_pb2
from ethos.elint.entities import account_assistant_pb2 as ethos_dot_elint_dot_entities_dot_account__assistant__pb2
try:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_account__assistant__pb2.google_dot_protobuf_dot_timestamp__pb2
except AttributeError:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_account__assistant__pb2.google.protobuf.timestamp_pb2
from ethos.elint.entities import space_knowledge_pb2 as ethos_dot_elint_dot_entities_dot_space__knowledge__pb2
try:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_space__knowledge__pb2.google_dot_protobuf_dot_timestamp__pb2
except AttributeError:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_space__knowledge__pb2.google.protobuf.timestamp_pb2
from ethos.elint.entities import generic_pb2 as ethos_dot_elint_dot_entities_dot_generic__pb2
try:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_generic__pb2.google_dot_protobuf_dot_timestamp__pb2
except AttributeError:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_generic__pb2.google.protobuf.timestamp_pb2
from ethos.elint.services.product.identity.account_assistant import access_account_assistant_pb2 as ethos_dot_elint_dot_services_dot_product_dot_identity_dot_account__assistant_dot_access__account__assistant__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ethos/elint/services/product/identity/account_assistant/action_account_assistant.proto',
  package='elint.services.product.identity.account.assistant',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\nVethos/elint/services/product/identity/account_assistant/action_account_assistant.proto\x12\x31\x65lint.services.product.identity.account.assistant\x1a\"ethos/elint/entities/account.proto\x1a,ethos/elint/entities/account_assistant.proto\x1a*ethos/elint/entities/space_knowledge.proto\x1a\"ethos/elint/entities/generic.proto\x1aVethos/elint/services/product/identity/account_assistant/access_account_assistant.proto\"\xb7\x02\n\x1a\x41\x63tOnAccountMessageRequest\x12y\n\x13\x61\x63\x63\x65ss_auth_details\x18\x01 \x01(\x0b\x32\\.elint.services.product.identity.account.assistant.AccountAssistantServicesAccessAuthDetails\x12I\n\x11\x63onnected_account\x18\x02 \x01(\x0b\x32..elint.entity.AccountAssistantConnectedAccount\x12\x42\n\x16space_knowledge_action\x18\x03 \x01(\x0e\x32\".elint.entity.SpaceKnowledgeAction\x12\x0f\n\x07message\x18\x04 \x01(\t2\xa4\x01\n\x1d\x41\x63tionAccountAssistantService\x12\x82\x01\n\x13\x41\x63tOnAccountMessage\x12M.elint.services.product.identity.account.assistant.ActOnAccountMessageRequest\x1a\x1a.elint.entity.ResponseMeta\"\x00\x62\x06proto3'
  ,
  dependencies=[ethos_dot_elint_dot_entities_dot_account__pb2.DESCRIPTOR,ethos_dot_elint_dot_entities_dot_account__assistant__pb2.DESCRIPTOR,ethos_dot_elint_dot_entities_dot_space__knowledge__pb2.DESCRIPTOR,ethos_dot_elint_dot_entities_dot_generic__pb2.DESCRIPTOR,ethos_dot_elint_dot_services_dot_product_dot_identity_dot_account__assistant_dot_access__account__assistant__pb2.DESCRIPTOR,])




_ACTONACCOUNTMESSAGEREQUEST = _descriptor.Descriptor(
  name='ActOnAccountMessageRequest',
  full_name='elint.services.product.identity.account.assistant.ActOnAccountMessageRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='access_auth_details', full_name='elint.services.product.identity.account.assistant.ActOnAccountMessageRequest.access_auth_details', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='connected_account', full_name='elint.services.product.identity.account.assistant.ActOnAccountMessageRequest.connected_account', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='space_knowledge_action', full_name='elint.services.product.identity.account.assistant.ActOnAccountMessageRequest.space_knowledge_action', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='elint.services.product.identity.account.assistant.ActOnAccountMessageRequest.message', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=392,
  serialized_end=703,
)

_ACTONACCOUNTMESSAGEREQUEST.fields_by_name['access_auth_details'].message_type = ethos_dot_elint_dot_services_dot_product_dot_identity_dot_account__assistant_dot_access__account__assistant__pb2._ACCOUNTASSISTANTSERVICESACCESSAUTHDETAILS
_ACTONACCOUNTMESSAGEREQUEST.fields_by_name['connected_account'].message_type = ethos_dot_elint_dot_entities_dot_account__assistant__pb2._ACCOUNTASSISTANTCONNECTEDACCOUNT
_ACTONACCOUNTMESSAGEREQUEST.fields_by_name['space_knowledge_action'].enum_type = ethos_dot_elint_dot_entities_dot_space__knowledge__pb2._SPACEKNOWLEDGEACTION
DESCRIPTOR.message_types_by_name['ActOnAccountMessageRequest'] = _ACTONACCOUNTMESSAGEREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ActOnAccountMessageRequest = _reflection.GeneratedProtocolMessageType('ActOnAccountMessageRequest', (_message.Message,), {
  'DESCRIPTOR' : _ACTONACCOUNTMESSAGEREQUEST,
  '__module__' : 'ethos.elint.services.product.identity.account_assistant.action_account_assistant_pb2'
  # @@protoc_insertion_point(class_scope:elint.services.product.identity.account.assistant.ActOnAccountMessageRequest)
  })
_sym_db.RegisterMessage(ActOnAccountMessageRequest)



_ACTIONACCOUNTASSISTANTSERVICE = _descriptor.ServiceDescriptor(
  name='ActionAccountAssistantService',
  full_name='elint.services.product.identity.account.assistant.ActionAccountAssistantService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=706,
  serialized_end=870,
  methods=[
  _descriptor.MethodDescriptor(
    name='ActOnAccountMessage',
    full_name='elint.services.product.identity.account.assistant.ActionAccountAssistantService.ActOnAccountMessage',
    index=0,
    containing_service=None,
    input_type=_ACTONACCOUNTMESSAGEREQUEST,
    output_type=ethos_dot_elint_dot_entities_dot_generic__pb2._RESPONSEMETA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ACTIONACCOUNTASSISTANTSERVICE)

DESCRIPTOR.services_by_name['ActionAccountAssistantService'] = _ACTIONACCOUNTASSISTANTSERVICE

# @@protoc_insertion_point(module_scope)
