# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from ethos.elint.services.product.knowledge import file_pb2 as ethos_dot_elint_dot_services_dot_product_dot_knowledge_dot_file__pb2


class FileServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FileUpload = channel.stream_unary(
                '/elint.services.product.knowledge.FileService/FileUpload',
                request_serializer=ethos_dot_elint_dot_services_dot_product_dot_knowledge_dot_file__pb2.Chunk.SerializeToString,
                response_deserializer=ethos_dot_elint_dot_services_dot_product_dot_knowledge_dot_file__pb2.Reply.FromString,
                )


class FileServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def FileUpload(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FileUpload': grpc.stream_unary_rpc_method_handler(
                    servicer.FileUpload,
                    request_deserializer=ethos_dot_elint_dot_services_dot_product_dot_knowledge_dot_file__pb2.Chunk.FromString,
                    response_serializer=ethos_dot_elint_dot_services_dot_product_dot_knowledge_dot_file__pb2.Reply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'elint.services.product.knowledge.FileService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FileService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def FileUpload(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/elint.services.product.knowledge.FileService/FileUpload',
            ethos_dot_elint_dot_services_dot_product_dot_knowledge_dot_file__pb2.Chunk.SerializeToString,
            ethos_dot_elint_dot_services_dot_product_dot_knowledge_dot_file__pb2.Reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
