# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ethos/elint/services/product/knowledge/file.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ethos/elint/services/product/knowledge/file.proto',
  package='elint.services.product.knowledge',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n1ethos/elint/services/product/knowledge/file.proto\x12 elint.services.product.knowledge\"\x84\x01\n\x11\x46ileUploadRequest\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\x0c\x12\x11\n\tupload_id\x18\x02 \x01(\t\x12K\n\x0bstatus_code\x18\x03 \x01(\x0e\x32\x36.elint.services.product.knowledge.FileUploadStatusCode\"\x85\x01\n\x12\x46ileUploadResponse\x12\x11\n\tupload_id\x18\x01 \x01(\t\x12K\n\x0bstatus_code\x18\x02 \x01(\x0e\x32\x36.elint.services.product.knowledge.FileUploadStatusCode\x12\x0f\n\x07message\x18\x03 \x01(\t\"\x17\n\x05\x43hunk\x12\x0e\n\x06\x62uffer\x18\x01 \x01(\x0c\"\x17\n\x05Reply\x12\x0e\n\x06length\x18\x01 \x01(\x05*G\n\x14\x46ileUploadStatusCode\x12\x0b\n\x07Unknown\x10\x00\x12\x06\n\x02Ok\x10\x01\x12\n\n\x06\x46\x61iled\x10\x02\x12\x0e\n\nInProgress\x10\x03\x32q\n\x0b\x46ileService\x12\x62\n\nFileUpload\x12\'.elint.services.product.knowledge.Chunk\x1a\'.elint.services.product.knowledge.Reply\"\x00(\x01\x62\x06proto3'
)

_FILEUPLOADSTATUSCODE = _descriptor.EnumDescriptor(
  name='FileUploadStatusCode',
  full_name='elint.services.product.knowledge.FileUploadStatusCode',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Unknown', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Ok', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='Failed', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='InProgress', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=408,
  serialized_end=479,
)
_sym_db.RegisterEnumDescriptor(_FILEUPLOADSTATUSCODE)

FileUploadStatusCode = enum_type_wrapper.EnumTypeWrapper(_FILEUPLOADSTATUSCODE)
Unknown = 0
Ok = 1
Failed = 2
InProgress = 3



_FILEUPLOADREQUEST = _descriptor.Descriptor(
  name='FileUploadRequest',
  full_name='elint.services.product.knowledge.FileUploadRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='content', full_name='elint.services.product.knowledge.FileUploadRequest.content', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='upload_id', full_name='elint.services.product.knowledge.FileUploadRequest.upload_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status_code', full_name='elint.services.product.knowledge.FileUploadRequest.status_code', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=88,
  serialized_end=220,
)


_FILEUPLOADRESPONSE = _descriptor.Descriptor(
  name='FileUploadResponse',
  full_name='elint.services.product.knowledge.FileUploadResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='upload_id', full_name='elint.services.product.knowledge.FileUploadResponse.upload_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status_code', full_name='elint.services.product.knowledge.FileUploadResponse.status_code', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='elint.services.product.knowledge.FileUploadResponse.message', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=223,
  serialized_end=356,
)


_CHUNK = _descriptor.Descriptor(
  name='Chunk',
  full_name='elint.services.product.knowledge.Chunk',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='buffer', full_name='elint.services.product.knowledge.Chunk.buffer', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=358,
  serialized_end=381,
)


_REPLY = _descriptor.Descriptor(
  name='Reply',
  full_name='elint.services.product.knowledge.Reply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='length', full_name='elint.services.product.knowledge.Reply.length', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=383,
  serialized_end=406,
)

_FILEUPLOADREQUEST.fields_by_name['status_code'].enum_type = _FILEUPLOADSTATUSCODE
_FILEUPLOADRESPONSE.fields_by_name['status_code'].enum_type = _FILEUPLOADSTATUSCODE
DESCRIPTOR.message_types_by_name['FileUploadRequest'] = _FILEUPLOADREQUEST
DESCRIPTOR.message_types_by_name['FileUploadResponse'] = _FILEUPLOADRESPONSE
DESCRIPTOR.message_types_by_name['Chunk'] = _CHUNK
DESCRIPTOR.message_types_by_name['Reply'] = _REPLY
DESCRIPTOR.enum_types_by_name['FileUploadStatusCode'] = _FILEUPLOADSTATUSCODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FileUploadRequest = _reflection.GeneratedProtocolMessageType('FileUploadRequest', (_message.Message,), {
  'DESCRIPTOR' : _FILEUPLOADREQUEST,
  '__module__' : 'ethos.elint.services.product.knowledge.file_pb2'
  # @@protoc_insertion_point(class_scope:elint.services.product.knowledge.FileUploadRequest)
  })
_sym_db.RegisterMessage(FileUploadRequest)

FileUploadResponse = _reflection.GeneratedProtocolMessageType('FileUploadResponse', (_message.Message,), {
  'DESCRIPTOR' : _FILEUPLOADRESPONSE,
  '__module__' : 'ethos.elint.services.product.knowledge.file_pb2'
  # @@protoc_insertion_point(class_scope:elint.services.product.knowledge.FileUploadResponse)
  })
_sym_db.RegisterMessage(FileUploadResponse)

Chunk = _reflection.GeneratedProtocolMessageType('Chunk', (_message.Message,), {
  'DESCRIPTOR' : _CHUNK,
  '__module__' : 'ethos.elint.services.product.knowledge.file_pb2'
  # @@protoc_insertion_point(class_scope:elint.services.product.knowledge.Chunk)
  })
_sym_db.RegisterMessage(Chunk)

Reply = _reflection.GeneratedProtocolMessageType('Reply', (_message.Message,), {
  'DESCRIPTOR' : _REPLY,
  '__module__' : 'ethos.elint.services.product.knowledge.file_pb2'
  # @@protoc_insertion_point(class_scope:elint.services.product.knowledge.Reply)
  })
_sym_db.RegisterMessage(Reply)



_FILESERVICE = _descriptor.ServiceDescriptor(
  name='FileService',
  full_name='elint.services.product.knowledge.FileService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=481,
  serialized_end=594,
  methods=[
  _descriptor.MethodDescriptor(
    name='FileUpload',
    full_name='elint.services.product.knowledge.FileService.FileUpload',
    index=0,
    containing_service=None,
    input_type=_CHUNK,
    output_type=_REPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_FILESERVICE)

DESCRIPTOR.services_by_name['FileService'] = _FILESERVICE

# @@protoc_insertion_point(module_scope)
