# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from ethos.elint.services.product.action import space_knowledge_action_pb2 as ethos_dot_elint_dot_services_dot_product_dot_action_dot_space__knowledge__action__pb2


class SpaceKnowledgeActionServiceStub(object):
    """Service Definitions
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AskQuestion = channel.unary_unary(
                '/elint.services.product.action.space.knowledge.SpaceKnowledgeActionService/AskQuestion',
                request_serializer=ethos_dot_elint_dot_services_dot_product_dot_action_dot_space__knowledge__action__pb2.AskQuestionRequest.SerializeToString,
                response_deserializer=ethos_dot_elint_dot_services_dot_product_dot_action_dot_space__knowledge__action__pb2.AskQuestionResponse.FromString,
                )


class SpaceKnowledgeActionServiceServicer(object):
    """Service Definitions
    """

    def AskQuestion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SpaceKnowledgeActionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AskQuestion': grpc.unary_unary_rpc_method_handler(
                    servicer.AskQuestion,
                    request_deserializer=ethos_dot_elint_dot_services_dot_product_dot_action_dot_space__knowledge__action__pb2.AskQuestionRequest.FromString,
                    response_serializer=ethos_dot_elint_dot_services_dot_product_dot_action_dot_space__knowledge__action__pb2.AskQuestionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'elint.services.product.action.space.knowledge.SpaceKnowledgeActionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SpaceKnowledgeActionService(object):
    """Service Definitions
    """

    @staticmethod
    def AskQuestion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/elint.services.product.action.space.knowledge.SpaceKnowledgeActionService/AskQuestion',
            ethos_dot_elint_dot_services_dot_product_dot_action_dot_space__knowledge__action__pb2.AskQuestionRequest.SerializeToString,
            ethos_dot_elint_dot_services_dot_product_dot_action_dot_space__knowledge__action__pb2.AskQuestionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
