# Use the official NGINX image as a base
FROM nginx:latest

# Copy the NGINX configuration file
COPY nginx.conf /etc/nginx/nginx.conf

# Create the directory for SSL certificates
RUN mkdir -p /app/certificates

# Copy SSL certificates and key into the container
COPY certificates/server.crt /app/certificates/server.crt
COPY certificates/server.key /app/certificates/server.key

# Expose ports
EXPOSE 80
EXPOSE 443
EXPOSE 8080

# Command to start NGINX
CMD ["nginx", "-g", "daemon off;"]