# Use the official NGINX image as a base
FROM nginx:latest

# Copy the NGINX configuration file
COPY nginx.conf /etc/nginx/nginx.conf


# Copy SSL certificates and key into the container
COPY certificates/server.crt /etc/nginx/ssl/server.crt
COPY certificates/server.key /etc/nginx/ssl/server.key

# Expose ports
EXPOSE 80
EXPOSE 15443

# Command to start NGINX
CMD ["nginx", "-g", "daemon off;"]