# -*- coding: utf-8 -*-

#   /*************************************************************************
#   *
#   * AMIT KUMAR KHETAN CONFIDENTIAL
#   * __________________
#   *
#   *  [2017] - [2021] Amit Kumar Khetan
#   *  All Rights Reserved.
#   *
#   * NOTICE:  All information contained herein is, and remains
#   * the property of Amit Kumar Khetan and its suppliers,
#   * if any.  The intellectual and technical concepts contained
#   * herein are proprietary to Amit Kumar Khetan
#   * and its suppliers and may be covered by U.S. and Foreign Patents,
#   * patents in process, and are protected by trade secret or copyright law.
#   * Dissemination of this information or reproduction of this material
#   * is strictly forbidden unless prior written permission is obtained
#   * from Amit Kumar Khetan.
#   */

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ethos/elint/services/product/knowledge/space_knowledge_domain_file_page_para/delete_space_knowledge_domain_file_page_para.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ethos.elint.entities import generic_pb2 as ethos_dot_elint_dot_entities_dot_generic__pb2
try:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_generic__pb2.google_dot_protobuf_dot_timestamp__pb2
except AttributeError:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_generic__pb2.google.protobuf.timestamp_pb2
from ethos.elint.services.product.knowledge.space_knowledge_domain_file_page import access_space_knowledge_domain_file_page_pb2 as ethos_dot_elint_dot_services_dot_product_dot_knowledge_dot_space__knowledge__domain__file__page_dot_access__space__knowledge__domain__file__page__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ethos/elint/services/product/knowledge/space_knowledge_domain_file_page_para/delete_space_knowledge_domain_file_page_para.proto',
  package='elint.services.product.knowledge.para',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x7f\x65thos/elint/services/product/knowledge/space_knowledge_domain_file_page_para/delete_space_knowledge_domain_file_page_para.proto\x12%elint.services.product.knowledge.para\x1a\"ethos/elint/entities/generic.proto\x1auethos/elint/services/product/knowledge/space_knowledge_domain_file_page/access_space_knowledge_domain_file_page.proto2\xc2\x01\n-DeleteSpaceKnowledgeDomainFilePageParaService\x12\x90\x01\n\x12\x44\x65leteParasForPage\x12\\.elint.services.product.knowledge.page.SpaceKnowledgeDomainFilePageServicesAccessAuthDetails\x1a\x1a.elint.entity.ResponseMeta\"\x00\x62\x06proto3'
  ,
  dependencies=[ethos_dot_elint_dot_entities_dot_generic__pb2.DESCRIPTOR,ethos_dot_elint_dot_services_dot_product_dot_knowledge_dot_space__knowledge__domain__file__page_dot_access__space__knowledge__domain__file__page__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_DELETESPACEKNOWLEDGEDOMAINFILEPAGEPARASERVICE = _descriptor.ServiceDescriptor(
  name='DeleteSpaceKnowledgeDomainFilePageParaService',
  full_name='elint.services.product.knowledge.para.DeleteSpaceKnowledgeDomainFilePageParaService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=326,
  serialized_end=520,
  methods=[
  _descriptor.MethodDescriptor(
    name='DeleteParasForPage',
    full_name='elint.services.product.knowledge.para.DeleteSpaceKnowledgeDomainFilePageParaService.DeleteParasForPage',
    index=0,
    containing_service=None,
    input_type=ethos_dot_elint_dot_services_dot_product_dot_knowledge_dot_space__knowledge__domain__file__page_dot_access__space__knowledge__domain__file__page__pb2._SPACEKNOWLEDGEDOMAINFILEPAGESERVICESACCESSAUTHDETAILS,
    output_type=ethos_dot_elint_dot_entities_dot_generic__pb2._RESPONSEMETA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DELETESPACEKNOWLEDGEDOMAINFILEPAGEPARASERVICE)

DESCRIPTOR.services_by_name['DeleteSpaceKnowledgeDomainFilePageParaService'] = _DELETESPACEKNOWLEDGEDOMAINFILEPAGEPARASERVICE

# @@protoc_insertion_point(module_scope)
