# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ethos/elint/services/product/knowledge/space_knowledge/discover_space_knowledge.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ethos.elint.entities import space_knowledge_domain_pb2 as ethos_dot_elint_dot_entities_dot_space__knowledge__domain__pb2
try:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_space__knowledge__domain__pb2.google_dot_protobuf_dot_timestamp__pb2
except AttributeError:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_space__knowledge__domain__pb2.google.protobuf.timestamp_pb2
from ethos.elint.entities import account_pb2 as ethos_dot_elint_dot_entities_dot_account__pb2
try:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_account__pb2.google_dot_protobuf_dot_timestamp__pb2
except AttributeError:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_account__pb2.google.protobuf.timestamp_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ethos/elint/services/product/knowledge/space_knowledge/discover_space_knowledge.proto',
  package='elint.services.product.knowledge.space',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\nUethos/elint/services/product/knowledge/space_knowledge/discover_space_knowledge.proto\x12&elint.services.product.knowledge.space\x1a\x31\x65thos/elint/entities/space_knowledge_domain.proto\x1a\"ethos/elint/entities/account.proto\"!\n\x1fGetSpaceKnowledgeDomainsRequest\"\"\n GetSpaceKnowledgeDomainsResponse2\xd1\x01\n\x1d\x44iscoverSpaceKnowledgeService\x12\xaf\x01\n\x18GetSpaceKnowledgeDomains\x12G.elint.services.product.knowledge.space.GetSpaceKnowledgeDomainsRequest\x1aH.elint.services.product.knowledge.space.GetSpaceKnowledgeDomainsResponse\"\x00\x62\x06proto3'
  ,
  dependencies=[ethos_dot_elint_dot_entities_dot_space__knowledge__domain__pb2.DESCRIPTOR,ethos_dot_elint_dot_entities_dot_account__pb2.DESCRIPTOR,])




_GETSPACEKNOWLEDGEDOMAINSREQUEST = _descriptor.Descriptor(
  name='GetSpaceKnowledgeDomainsRequest',
  full_name='elint.services.product.knowledge.space.GetSpaceKnowledgeDomainsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=216,
  serialized_end=249,
)


_GETSPACEKNOWLEDGEDOMAINSRESPONSE = _descriptor.Descriptor(
  name='GetSpaceKnowledgeDomainsResponse',
  full_name='elint.services.product.knowledge.space.GetSpaceKnowledgeDomainsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=251,
  serialized_end=285,
)

DESCRIPTOR.message_types_by_name['GetSpaceKnowledgeDomainsRequest'] = _GETSPACEKNOWLEDGEDOMAINSREQUEST
DESCRIPTOR.message_types_by_name['GetSpaceKnowledgeDomainsResponse'] = _GETSPACEKNOWLEDGEDOMAINSRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetSpaceKnowledgeDomainsRequest = _reflection.GeneratedProtocolMessageType('GetSpaceKnowledgeDomainsRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETSPACEKNOWLEDGEDOMAINSREQUEST,
  '__module__' : 'ethos.elint.services.product.knowledge.space_knowledge.discover_space_knowledge_pb2'
  # @@protoc_insertion_point(class_scope:elint.services.product.knowledge.space.GetSpaceKnowledgeDomainsRequest)
  })
_sym_db.RegisterMessage(GetSpaceKnowledgeDomainsRequest)

GetSpaceKnowledgeDomainsResponse = _reflection.GeneratedProtocolMessageType('GetSpaceKnowledgeDomainsResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETSPACEKNOWLEDGEDOMAINSRESPONSE,
  '__module__' : 'ethos.elint.services.product.knowledge.space_knowledge.discover_space_knowledge_pb2'
  # @@protoc_insertion_point(class_scope:elint.services.product.knowledge.space.GetSpaceKnowledgeDomainsResponse)
  })
_sym_db.RegisterMessage(GetSpaceKnowledgeDomainsResponse)



_DISCOVERSPACEKNOWLEDGESERVICE = _descriptor.ServiceDescriptor(
  name='DiscoverSpaceKnowledgeService',
  full_name='elint.services.product.knowledge.space.DiscoverSpaceKnowledgeService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=288,
  serialized_end=497,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetSpaceKnowledgeDomains',
    full_name='elint.services.product.knowledge.space.DiscoverSpaceKnowledgeService.GetSpaceKnowledgeDomains',
    index=0,
    containing_service=None,
    input_type=_GETSPACEKNOWLEDGEDOMAINSREQUEST,
    output_type=_GETSPACEKNOWLEDGEDOMAINSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DISCOVERSPACEKNOWLEDGESERVICE)

DESCRIPTOR.services_by_name['DiscoverSpaceKnowledgeService'] = _DISCOVERSPACEKNOWLEDGESERVICE

# @@protoc_insertion_point(module_scope)
