# -*- coding: utf-8 -*-

#   /*************************************************************************
#   *
#   * AMIT KUMAR KHETAN CONFIDENTIAL
#   * __________________
#   *
#   *  [2017] - [2021] Amit Kumar Khetan
#   *  All Rights Reserved.
#   *
#   * NOTICE:  All information contained herein is, and remains
#   * the property of Amit Kumar Khetan and its suppliers,
#   * if any.  The intellectual and technical concepts contained
#   * herein are proprietary to Amit Kumar Khetan
#   * and its suppliers and may be covered by U.S. and Foreign Patents,
#   * patents in process, and are protected by trade secret or copyright law.
#   * Dissemination of this information or reproduction of this material
#   * is strictly forbidden unless prior written permission is obtained
#   * from Amit Kumar Khetan.
#   */

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ethos/elint/services/product/knowledge/space_knowledge_domain/update_space_knowledge_domain.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ethos/elint/services/product/knowledge/space_knowledge_domain/update_space_knowledge_domain.proto',
  package='elint.services.product.knowledge.domain',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\naethos/elint/services/product/knowledge/space_knowledge_domain/update_space_knowledge_domain.proto\x12\'elint.services.product.knowledge.domain\"\'\n%UpdateSpaceKnowledgeDomainNameRequest\"(\n&UpdateSpaceKnowledgeDomainNameResponse2\xe9\x01\n!UpdateSpaceKnowledgeDomainService\x12\xc3\x01\n\x1eUpdateSpaceKnowledgeDomainName\x12N.elint.services.product.knowledge.domain.UpdateSpaceKnowledgeDomainNameRequest\x1aO.elint.services.product.knowledge.domain.UpdateSpaceKnowledgeDomainNameResponse\"\x00\x62\x06proto3'
)




_UPDATESPACEKNOWLEDGEDOMAINNAMEREQUEST = _descriptor.Descriptor(
  name='UpdateSpaceKnowledgeDomainNameRequest',
  full_name='elint.services.product.knowledge.domain.UpdateSpaceKnowledgeDomainNameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=142,
  serialized_end=181,
)


_UPDATESPACEKNOWLEDGEDOMAINNAMERESPONSE = _descriptor.Descriptor(
  name='UpdateSpaceKnowledgeDomainNameResponse',
  full_name='elint.services.product.knowledge.domain.UpdateSpaceKnowledgeDomainNameResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=183,
  serialized_end=223,
)

DESCRIPTOR.message_types_by_name['UpdateSpaceKnowledgeDomainNameRequest'] = _UPDATESPACEKNOWLEDGEDOMAINNAMEREQUEST
DESCRIPTOR.message_types_by_name['UpdateSpaceKnowledgeDomainNameResponse'] = _UPDATESPACEKNOWLEDGEDOMAINNAMERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UpdateSpaceKnowledgeDomainNameRequest = _reflection.GeneratedProtocolMessageType('UpdateSpaceKnowledgeDomainNameRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPDATESPACEKNOWLEDGEDOMAINNAMEREQUEST,
  '__module__' : 'ethos.elint.services.product.knowledge.space_knowledge_domain.update_space_knowledge_domain_pb2'
  # @@protoc_insertion_point(class_scope:elint.services.product.knowledge.domain.UpdateSpaceKnowledgeDomainNameRequest)
  })
_sym_db.RegisterMessage(UpdateSpaceKnowledgeDomainNameRequest)

UpdateSpaceKnowledgeDomainNameResponse = _reflection.GeneratedProtocolMessageType('UpdateSpaceKnowledgeDomainNameResponse', (_message.Message,), {
  'DESCRIPTOR' : _UPDATESPACEKNOWLEDGEDOMAINNAMERESPONSE,
  '__module__' : 'ethos.elint.services.product.knowledge.space_knowledge_domain.update_space_knowledge_domain_pb2'
  # @@protoc_insertion_point(class_scope:elint.services.product.knowledge.domain.UpdateSpaceKnowledgeDomainNameResponse)
  })
_sym_db.RegisterMessage(UpdateSpaceKnowledgeDomainNameResponse)



_UPDATESPACEKNOWLEDGEDOMAINSERVICE = _descriptor.ServiceDescriptor(
  name='UpdateSpaceKnowledgeDomainService',
  full_name='elint.services.product.knowledge.domain.UpdateSpaceKnowledgeDomainService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=226,
  serialized_end=459,
  methods=[
  _descriptor.MethodDescriptor(
    name='UpdateSpaceKnowledgeDomainName',
    full_name='elint.services.product.knowledge.domain.UpdateSpaceKnowledgeDomainService.UpdateSpaceKnowledgeDomainName',
    index=0,
    containing_service=None,
    input_type=_UPDATESPACEKNOWLEDGEDOMAINNAMEREQUEST,
    output_type=_UPDATESPACEKNOWLEDGEDOMAINNAMERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_UPDATESPACEKNOWLEDGEDOMAINSERVICE)

DESCRIPTOR.services_by_name['UpdateSpaceKnowledgeDomainService'] = _UPDATESPACEKNOWLEDGEDOMAINSERVICE

# @@protoc_insertion_point(module_scope)
