# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from ethos.elint.entities import generic_pb2 as ethos_dot_elint_dot_entities_dot_generic__pb2
from ethos.elint.services.product.identity.universe import create_universe_pb2 as ethos_dot_elint_dot_services_dot_product_dot_identity_dot_universe_dot_create__universe__pb2


class CreateUniverseServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RecognizeCountryUniverse = channel.unary_unary(
                '/elint.services.product.identity.universe.CreateUniverseService/RecognizeCountryUniverse',
                request_serializer=ethos_dot_elint_dot_services_dot_product_dot_identity_dot_universe_dot_create__universe__pb2.RecognizeCountryUniverseRequest.SerializeToString,
                response_deserializer=ethos_dot_elint_dot_entities_dot_generic__pb2.ResponseMeta.FromString,
                )


class CreateUniverseServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RecognizeCountryUniverse(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CreateUniverseServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RecognizeCountryUniverse': grpc.unary_unary_rpc_method_handler(
                    servicer.RecognizeCountryUniverse,
                    request_deserializer=ethos_dot_elint_dot_services_dot_product_dot_identity_dot_universe_dot_create__universe__pb2.RecognizeCountryUniverseRequest.FromString,
                    response_serializer=ethos_dot_elint_dot_entities_dot_generic__pb2.ResponseMeta.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'elint.services.product.identity.universe.CreateUniverseService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CreateUniverseService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RecognizeCountryUniverse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/elint.services.product.identity.universe.CreateUniverseService/RecognizeCountryUniverse',
            ethos_dot_elint_dot_services_dot_product_dot_identity_dot_universe_dot_create__universe__pb2.RecognizeCountryUniverseRequest.SerializeToString,
            ethos_dot_elint_dot_entities_dot_generic__pb2.ResponseMeta.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
