# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from ethos.elint.services.product.conversation.message.account_assistant import receive_account_assistant_message_pb2 as ethos_dot_elint_dot_services_dot_product_dot_conversation_dot_message_dot_account__assistant_dot_receive__account__assistant__message__pb2


class ReceiveAccountAssistantMessageServiceStub(object):
    """Service Definitions
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReceiveMessageFromAccount = channel.unary_unary(
                '/elint.services.product.conversation.message.account.assistant.ReceiveAccountAssistantMessageService/ReceiveMessageFromAccount',
                request_serializer=ethos_dot_elint_dot_services_dot_product_dot_conversation_dot_message_dot_account__assistant_dot_receive__account__assistant__message__pb2.MessageFromAccount.SerializeToString,
                response_deserializer=ethos_dot_elint_dot_services_dot_product_dot_conversation_dot_message_dot_account__assistant_dot_receive__account__assistant__message__pb2.MessageFromAccountReceived.FromString,
                )


class ReceiveAccountAssistantMessageServiceServicer(object):
    """Service Definitions
    """

    def ReceiveMessageFromAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReceiveAccountAssistantMessageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReceiveMessageFromAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.ReceiveMessageFromAccount,
                    request_deserializer=ethos_dot_elint_dot_services_dot_product_dot_conversation_dot_message_dot_account__assistant_dot_receive__account__assistant__message__pb2.MessageFromAccount.FromString,
                    response_serializer=ethos_dot_elint_dot_services_dot_product_dot_conversation_dot_message_dot_account__assistant_dot_receive__account__assistant__message__pb2.MessageFromAccountReceived.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'elint.services.product.conversation.message.account.assistant.ReceiveAccountAssistantMessageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ReceiveAccountAssistantMessageService(object):
    """Service Definitions
    """

    @staticmethod
    def ReceiveMessageFromAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/elint.services.product.conversation.message.account.assistant.ReceiveAccountAssistantMessageService/ReceiveMessageFromAccount',
            ethos_dot_elint_dot_services_dot_product_dot_conversation_dot_message_dot_account__assistant_dot_receive__account__assistant__message__pb2.MessageFromAccount.SerializeToString,
            ethos_dot_elint_dot_services_dot_product_dot_conversation_dot_message_dot_account__assistant_dot_receive__account__assistant__message__pb2.MessageFromAccountReceived.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
