# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from ethos.elint.entities import generic_pb2 as ethos_dot_elint_dot_entities_dot_generic__pb2
from ethos.elint.services.product.identity.account import notify_account_pb2 as ethos_dot_elint_dot_services_dot_product_dot_identity_dot_account_dot_notify__account__pb2


class NotifyAccountServiceStub(object):
    """Service Definitions
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.NewReceivedMessageFromAccountAssistant = channel.unary_unary(
                '/elint.services.product.identity.account.NotifyAccountService/NewReceivedMessageFromAccountAssistant',
                request_serializer=ethos_dot_elint_dot_services_dot_product_dot_identity_dot_account_dot_notify__account__pb2.NewReceivedMessageFromAccountAssistantRequest.SerializeToString,
                response_deserializer=ethos_dot_elint_dot_entities_dot_generic__pb2.ResponseMeta.FromString,
                )
        self.NewReceivedMessageFromAccount = channel.unary_unary(
                '/elint.services.product.identity.account.NotifyAccountService/NewReceivedMessageFromAccount',
                request_serializer=ethos_dot_elint_dot_services_dot_product_dot_identity_dot_account_dot_notify__account__pb2.NewReceivedMessageFromAccountRequest.SerializeToString,
                response_deserializer=ethos_dot_elint_dot_entities_dot_generic__pb2.ResponseMeta.FromString,
                )
        self.AccountConnectedAccountNotification = channel.unary_unary(
                '/elint.services.product.identity.account.NotifyAccountService/AccountConnectedAccountNotification',
                request_serializer=ethos_dot_elint_dot_services_dot_product_dot_identity_dot_account_dot_notify__account__pb2.AccountConnectedAccountNotificationRequest.SerializeToString,
                response_deserializer=ethos_dot_elint_dot_entities_dot_generic__pb2.ResponseMeta.FromString,
                )
        self.UpdateAccountDeviceDetails = channel.unary_unary(
                '/elint.services.product.identity.account.NotifyAccountService/UpdateAccountDeviceDetails',
                request_serializer=ethos_dot_elint_dot_services_dot_product_dot_identity_dot_account_dot_notify__account__pb2.UpdateAccountDeviceDetailsRequest.SerializeToString,
                response_deserializer=ethos_dot_elint_dot_entities_dot_generic__pb2.ResponseMeta.FromString,
                )


class NotifyAccountServiceServicer(object):
    """Service Definitions
    """

    def NewReceivedMessageFromAccountAssistant(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NewReceivedMessageFromAccount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AccountConnectedAccountNotification(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateAccountDeviceDetails(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NotifyAccountServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'NewReceivedMessageFromAccountAssistant': grpc.unary_unary_rpc_method_handler(
                    servicer.NewReceivedMessageFromAccountAssistant,
                    request_deserializer=ethos_dot_elint_dot_services_dot_product_dot_identity_dot_account_dot_notify__account__pb2.NewReceivedMessageFromAccountAssistantRequest.FromString,
                    response_serializer=ethos_dot_elint_dot_entities_dot_generic__pb2.ResponseMeta.SerializeToString,
            ),
            'NewReceivedMessageFromAccount': grpc.unary_unary_rpc_method_handler(
                    servicer.NewReceivedMessageFromAccount,
                    request_deserializer=ethos_dot_elint_dot_services_dot_product_dot_identity_dot_account_dot_notify__account__pb2.NewReceivedMessageFromAccountRequest.FromString,
                    response_serializer=ethos_dot_elint_dot_entities_dot_generic__pb2.ResponseMeta.SerializeToString,
            ),
            'AccountConnectedAccountNotification': grpc.unary_unary_rpc_method_handler(
                    servicer.AccountConnectedAccountNotification,
                    request_deserializer=ethos_dot_elint_dot_services_dot_product_dot_identity_dot_account_dot_notify__account__pb2.AccountConnectedAccountNotificationRequest.FromString,
                    response_serializer=ethos_dot_elint_dot_entities_dot_generic__pb2.ResponseMeta.SerializeToString,
            ),
            'UpdateAccountDeviceDetails': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateAccountDeviceDetails,
                    request_deserializer=ethos_dot_elint_dot_services_dot_product_dot_identity_dot_account_dot_notify__account__pb2.UpdateAccountDeviceDetailsRequest.FromString,
                    response_serializer=ethos_dot_elint_dot_entities_dot_generic__pb2.ResponseMeta.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'elint.services.product.identity.account.NotifyAccountService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class NotifyAccountService(object):
    """Service Definitions
    """

    @staticmethod
    def NewReceivedMessageFromAccountAssistant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/elint.services.product.identity.account.NotifyAccountService/NewReceivedMessageFromAccountAssistant',
            ethos_dot_elint_dot_services_dot_product_dot_identity_dot_account_dot_notify__account__pb2.NewReceivedMessageFromAccountAssistantRequest.SerializeToString,
            ethos_dot_elint_dot_entities_dot_generic__pb2.ResponseMeta.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def NewReceivedMessageFromAccount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/elint.services.product.identity.account.NotifyAccountService/NewReceivedMessageFromAccount',
            ethos_dot_elint_dot_services_dot_product_dot_identity_dot_account_dot_notify__account__pb2.NewReceivedMessageFromAccountRequest.SerializeToString,
            ethos_dot_elint_dot_entities_dot_generic__pb2.ResponseMeta.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AccountConnectedAccountNotification(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/elint.services.product.identity.account.NotifyAccountService/AccountConnectedAccountNotification',
            ethos_dot_elint_dot_services_dot_product_dot_identity_dot_account_dot_notify__account__pb2.AccountConnectedAccountNotificationRequest.SerializeToString,
            ethos_dot_elint_dot_entities_dot_generic__pb2.ResponseMeta.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateAccountDeviceDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/elint.services.product.identity.account.NotifyAccountService/UpdateAccountDeviceDetails',
            ethos_dot_elint_dot_services_dot_product_dot_identity_dot_account_dot_notify__account__pb2.UpdateAccountDeviceDetailsRequest.SerializeToString,
            ethos_dot_elint_dot_entities_dot_generic__pb2.ResponseMeta.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
