# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ethos/elint/services/product/identity/account/notify_account.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ethos.elint.entities import account_pb2 as ethos_dot_elint_dot_entities_dot_account__pb2
try:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_account__pb2.google_dot_protobuf_dot_timestamp__pb2
except AttributeError:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_account__pb2.google.protobuf.timestamp_pb2
from ethos.elint.entities import generic_pb2 as ethos_dot_elint_dot_entities_dot_generic__pb2
try:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_generic__pb2.google_dot_protobuf_dot_timestamp__pb2
except AttributeError:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_generic__pb2.google.protobuf.timestamp_pb2
from ethos.elint.services.product.identity.account import access_account_pb2 as ethos_dot_elint_dot_services_dot_product_dot_identity_dot_account_dot_access__account__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ethos/elint/services/product/identity/account/notify_account.proto',
  package='elint.services.product.identity.account',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\nBethos/elint/services/product/identity/account/notify_account.proto\x12\'elint.services.product.identity.account\x1a\"ethos/elint/entities/account.proto\x1a\"ethos/elint/entities/generic.proto\x1a\x42\x65thos/elint/services/product/identity/account/access_account.proto\"\xc7\x01\n-NewReceivedMessageFromAccountAssistantRequest\x12\x12\n\naccount_id\x18\x01 \x01(\t\x12S\n\x1b\x63onnected_account_assistant\x18\x02 \x01(\x0b\x32..elint.entity.AccountConnectedAccountAssistant\x12-\n%account_assistant_received_message_id\x18\x03 \x01(\t\"j\n$NewReceivedMessageFromAccountRequest\x12\x12\n\naccount_id\x18\x01 \x01(\t\x12\x1d\n\x15\x63onnecting_account_id\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"\xa9\x01\n*AccountConnectedAccountNotificationRequest\x12&\n\x07\x61\x63\x63ount\x18\x01 \x01(\x0b\x32\x15.elint.entity.Account\x12S\n$connecting_account_connected_account\x18\x02 \x01(\x0b\x32%.elint.entity.AccountConnectedAccount\"\xcf\x01\n!UpdateAccountDeviceDetailsRequest\x12\x66\n\x13\x61\x63\x63\x65ss_auth_details\x18\x01 \x01(\x0b\x32I.elint.services.product.identity.account.AccountServicesAccessAuthDetails\x12\x42\n\x16\x61\x63\x63ount_device_details\x18\x02 \x01(\x0b\x32\".elint.entity.AccountDeviceDetails2\xea\x04\n\x14NotifyAccountService\x12\x9e\x01\n&NewReceivedMessageFromAccountAssistant\x12V.elint.services.product.identity.account.NewReceivedMessageFromAccountAssistantRequest\x1a\x1a.elint.entity.ResponseMeta\"\x00\x12\x8c\x01\n\x1dNewReceivedMessageFromAccount\x12M.elint.services.product.identity.account.NewReceivedMessageFromAccountRequest\x1a\x1a.elint.entity.ResponseMeta\"\x00\x12\x98\x01\n#AccountConnectedAccountNotification\x12S.elint.services.product.identity.account.AccountConnectedAccountNotificationRequest\x1a\x1a.elint.entity.ResponseMeta\"\x00\x12\x86\x01\n\x1aUpdateAccountDeviceDetails\x12J.elint.services.product.identity.account.UpdateAccountDeviceDetailsRequest\x1a\x1a.elint.entity.ResponseMeta\"\x00\x62\x06proto3'
  ,
  dependencies=[ethos_dot_elint_dot_entities_dot_account__pb2.DESCRIPTOR,ethos_dot_elint_dot_entities_dot_generic__pb2.DESCRIPTOR,ethos_dot_elint_dot_services_dot_product_dot_identity_dot_account_dot_access__account__pb2.DESCRIPTOR,])




_NEWRECEIVEDMESSAGEFROMACCOUNTASSISTANTREQUEST = _descriptor.Descriptor(
  name='NewReceivedMessageFromAccountAssistantRequest',
  full_name='elint.services.product.identity.account.NewReceivedMessageFromAccountAssistantRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='account_id', full_name='elint.services.product.identity.account.NewReceivedMessageFromAccountAssistantRequest.account_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='connected_account_assistant', full_name='elint.services.product.identity.account.NewReceivedMessageFromAccountAssistantRequest.connected_account_assistant', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='account_assistant_received_message_id', full_name='elint.services.product.identity.account.NewReceivedMessageFromAccountAssistantRequest.account_assistant_received_message_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=252,
  serialized_end=451,
)


_NEWRECEIVEDMESSAGEFROMACCOUNTREQUEST = _descriptor.Descriptor(
  name='NewReceivedMessageFromAccountRequest',
  full_name='elint.services.product.identity.account.NewReceivedMessageFromAccountRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='account_id', full_name='elint.services.product.identity.account.NewReceivedMessageFromAccountRequest.account_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='connecting_account_id', full_name='elint.services.product.identity.account.NewReceivedMessageFromAccountRequest.connecting_account_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='elint.services.product.identity.account.NewReceivedMessageFromAccountRequest.message', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=453,
  serialized_end=559,
)


_ACCOUNTCONNECTEDACCOUNTNOTIFICATIONREQUEST = _descriptor.Descriptor(
  name='AccountConnectedAccountNotificationRequest',
  full_name='elint.services.product.identity.account.AccountConnectedAccountNotificationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='account', full_name='elint.services.product.identity.account.AccountConnectedAccountNotificationRequest.account', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='connecting_account_connected_account', full_name='elint.services.product.identity.account.AccountConnectedAccountNotificationRequest.connecting_account_connected_account', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=562,
  serialized_end=731,
)


_UPDATEACCOUNTDEVICEDETAILSREQUEST = _descriptor.Descriptor(
  name='UpdateAccountDeviceDetailsRequest',
  full_name='elint.services.product.identity.account.UpdateAccountDeviceDetailsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='access_auth_details', full_name='elint.services.product.identity.account.UpdateAccountDeviceDetailsRequest.access_auth_details', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='account_device_details', full_name='elint.services.product.identity.account.UpdateAccountDeviceDetailsRequest.account_device_details', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=734,
  serialized_end=941,
)

_NEWRECEIVEDMESSAGEFROMACCOUNTASSISTANTREQUEST.fields_by_name['connected_account_assistant'].message_type = ethos_dot_elint_dot_entities_dot_account__pb2._ACCOUNTCONNECTEDACCOUNTASSISTANT
_ACCOUNTCONNECTEDACCOUNTNOTIFICATIONREQUEST.fields_by_name['account'].message_type = ethos_dot_elint_dot_entities_dot_account__pb2._ACCOUNT
_ACCOUNTCONNECTEDACCOUNTNOTIFICATIONREQUEST.fields_by_name['connecting_account_connected_account'].message_type = ethos_dot_elint_dot_entities_dot_account__pb2._ACCOUNTCONNECTEDACCOUNT
_UPDATEACCOUNTDEVICEDETAILSREQUEST.fields_by_name['access_auth_details'].message_type = ethos_dot_elint_dot_services_dot_product_dot_identity_dot_account_dot_access__account__pb2._ACCOUNTSERVICESACCESSAUTHDETAILS
_UPDATEACCOUNTDEVICEDETAILSREQUEST.fields_by_name['account_device_details'].message_type = ethos_dot_elint_dot_entities_dot_account__pb2._ACCOUNTDEVICEDETAILS
DESCRIPTOR.message_types_by_name['NewReceivedMessageFromAccountAssistantRequest'] = _NEWRECEIVEDMESSAGEFROMACCOUNTASSISTANTREQUEST
DESCRIPTOR.message_types_by_name['NewReceivedMessageFromAccountRequest'] = _NEWRECEIVEDMESSAGEFROMACCOUNTREQUEST
DESCRIPTOR.message_types_by_name['AccountConnectedAccountNotificationRequest'] = _ACCOUNTCONNECTEDACCOUNTNOTIFICATIONREQUEST
DESCRIPTOR.message_types_by_name['UpdateAccountDeviceDetailsRequest'] = _UPDATEACCOUNTDEVICEDETAILSREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NewReceivedMessageFromAccountAssistantRequest = _reflection.GeneratedProtocolMessageType('NewReceivedMessageFromAccountAssistantRequest', (_message.Message,), {
  'DESCRIPTOR' : _NEWRECEIVEDMESSAGEFROMACCOUNTASSISTANTREQUEST,
  '__module__' : 'ethos.elint.services.product.identity.account.notify_account_pb2'
  # @@protoc_insertion_point(class_scope:elint.services.product.identity.account.NewReceivedMessageFromAccountAssistantRequest)
  })
_sym_db.RegisterMessage(NewReceivedMessageFromAccountAssistantRequest)

NewReceivedMessageFromAccountRequest = _reflection.GeneratedProtocolMessageType('NewReceivedMessageFromAccountRequest', (_message.Message,), {
  'DESCRIPTOR' : _NEWRECEIVEDMESSAGEFROMACCOUNTREQUEST,
  '__module__' : 'ethos.elint.services.product.identity.account.notify_account_pb2'
  # @@protoc_insertion_point(class_scope:elint.services.product.identity.account.NewReceivedMessageFromAccountRequest)
  })
_sym_db.RegisterMessage(NewReceivedMessageFromAccountRequest)

AccountConnectedAccountNotificationRequest = _reflection.GeneratedProtocolMessageType('AccountConnectedAccountNotificationRequest', (_message.Message,), {
  'DESCRIPTOR' : _ACCOUNTCONNECTEDACCOUNTNOTIFICATIONREQUEST,
  '__module__' : 'ethos.elint.services.product.identity.account.notify_account_pb2'
  # @@protoc_insertion_point(class_scope:elint.services.product.identity.account.AccountConnectedAccountNotificationRequest)
  })
_sym_db.RegisterMessage(AccountConnectedAccountNotificationRequest)

UpdateAccountDeviceDetailsRequest = _reflection.GeneratedProtocolMessageType('UpdateAccountDeviceDetailsRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEACCOUNTDEVICEDETAILSREQUEST,
  '__module__' : 'ethos.elint.services.product.identity.account.notify_account_pb2'
  # @@protoc_insertion_point(class_scope:elint.services.product.identity.account.UpdateAccountDeviceDetailsRequest)
  })
_sym_db.RegisterMessage(UpdateAccountDeviceDetailsRequest)



_NOTIFYACCOUNTSERVICE = _descriptor.ServiceDescriptor(
  name='NotifyAccountService',
  full_name='elint.services.product.identity.account.NotifyAccountService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=944,
  serialized_end=1562,
  methods=[
  _descriptor.MethodDescriptor(
    name='NewReceivedMessageFromAccountAssistant',
    full_name='elint.services.product.identity.account.NotifyAccountService.NewReceivedMessageFromAccountAssistant',
    index=0,
    containing_service=None,
    input_type=_NEWRECEIVEDMESSAGEFROMACCOUNTASSISTANTREQUEST,
    output_type=ethos_dot_elint_dot_entities_dot_generic__pb2._RESPONSEMETA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='NewReceivedMessageFromAccount',
    full_name='elint.services.product.identity.account.NotifyAccountService.NewReceivedMessageFromAccount',
    index=1,
    containing_service=None,
    input_type=_NEWRECEIVEDMESSAGEFROMACCOUNTREQUEST,
    output_type=ethos_dot_elint_dot_entities_dot_generic__pb2._RESPONSEMETA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='AccountConnectedAccountNotification',
    full_name='elint.services.product.identity.account.NotifyAccountService.AccountConnectedAccountNotification',
    index=2,
    containing_service=None,
    input_type=_ACCOUNTCONNECTEDACCOUNTNOTIFICATIONREQUEST,
    output_type=ethos_dot_elint_dot_entities_dot_generic__pb2._RESPONSEMETA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateAccountDeviceDetails',
    full_name='elint.services.product.identity.account.NotifyAccountService.UpdateAccountDeviceDetails',
    index=3,
    containing_service=None,
    input_type=_UPDATEACCOUNTDEVICEDETAILSREQUEST,
    output_type=ethos_dot_elint_dot_entities_dot_generic__pb2._RESPONSEMETA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_NOTIFYACCOUNTSERVICE)

DESCRIPTOR.services_by_name['NotifyAccountService'] = _NOTIFYACCOUNTSERVICE

# @@protoc_insertion_point(module_scope)
