# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ethos/elint/services/product/identity/account/space_gateway_account.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ethos.elint.entities import account_pb2 as ethos_dot_elint_dot_entities_dot_account__pb2
try:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_account__pb2.google_dot_protobuf_dot_timestamp__pb2
except AttributeError:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_account__pb2.google.protobuf.timestamp_pb2
from ethos.elint.entities import generic_pb2 as ethos_dot_elint_dot_entities_dot_generic__pb2
try:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_generic__pb2.google_dot_protobuf_dot_timestamp__pb2
except AttributeError:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_generic__pb2.google.protobuf.timestamp_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ethos/elint/services/product/identity/account/space_gateway_account.proto',
  package='elint.services.product.identity',
  syntax='proto3',
  serialized_options=b'\n com.ethos.elint.services.productP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\nIethos/elint/services/product/identity/account/space_gateway_account.proto\x12\x1f\x65lint.services.product.identity\x1a\"ethos/elint/entities/account.proto\x1a\"ethos/elint/entities/generic.proto\"\xc2\x01\n&AccountSpaceGatewaySessionTokenDetails\x12>\n\nspace_kind\x18\x01 \x01(\x0e\x32*.elint.services.product.identity.SpaceKind\x12X\n#space_gateway_session_token_details\x18\x02 \x01(\x0b\x32+.elint.entity.PersistentSessionTokenDetails\"\xe9\x01\n\x19SpaceGatewayAccessRequest\x12Z\n%identity_access_session_token_details\x18\x01 \x01(\x0b\x32+.elint.entity.PersistentSessionTokenDetails\x12>\n\nspace_kind\x18\x02 \x01(\x0e\x32*.elint.services.product.identity.SpaceKind\x12\x30\n\x0crequested_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x9a\x01\n\x1aSpaceGatewayAccessResponse\x12|\n+account_space_gateway_session_token_details\x18\x01 \x01(\x0b\x32G.elint.services.product.identity.AccountSpaceGatewaySessionTokenDetails*?\n\tSpaceKind\x12\r\n\tKNOWLEDGE\x10\x00\x12\x0b\n\x07PRODUCT\x10\x01\x12\x0b\n\x07SERVICE\x10\x02\x12\t\n\x05THING\x10\x03\x32\xae\x01\n\x1aSpaceGatewayAccountService\x12\x8f\x01\n\x12SpaceGatewayAccess\x12:.elint.services.product.identity.SpaceGatewayAccessRequest\x1a;.elint.services.product.identity.SpaceGatewayAccessResponse\"\x00\x42$\n com.ethos.elint.services.productP\x01\x62\x06proto3'
  ,
  dependencies=[ethos_dot_elint_dot_entities_dot_account__pb2.DESCRIPTOR,ethos_dot_elint_dot_entities_dot_generic__pb2.DESCRIPTOR,])

_SPACEKIND = _descriptor.EnumDescriptor(
  name='SpaceKind',
  full_name='elint.services.product.identity.SpaceKind',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='KNOWLEDGE', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='PRODUCT', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SERVICE', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='THING', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=772,
  serialized_end=835,
)
_sym_db.RegisterEnumDescriptor(_SPACEKIND)

SpaceKind = enum_type_wrapper.EnumTypeWrapper(_SPACEKIND)
KNOWLEDGE = 0
PRODUCT = 1
SERVICE = 2
THING = 3



_ACCOUNTSPACEGATEWAYSESSIONTOKENDETAILS = _descriptor.Descriptor(
  name='AccountSpaceGatewaySessionTokenDetails',
  full_name='elint.services.product.identity.AccountSpaceGatewaySessionTokenDetails',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='space_kind', full_name='elint.services.product.identity.AccountSpaceGatewaySessionTokenDetails.space_kind', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='space_gateway_session_token_details', full_name='elint.services.product.identity.AccountSpaceGatewaySessionTokenDetails.space_gateway_session_token_details', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=183,
  serialized_end=377,
)


_SPACEGATEWAYACCESSREQUEST = _descriptor.Descriptor(
  name='SpaceGatewayAccessRequest',
  full_name='elint.services.product.identity.SpaceGatewayAccessRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='identity_access_session_token_details', full_name='elint.services.product.identity.SpaceGatewayAccessRequest.identity_access_session_token_details', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='space_kind', full_name='elint.services.product.identity.SpaceGatewayAccessRequest.space_kind', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='requested_at', full_name='elint.services.product.identity.SpaceGatewayAccessRequest.requested_at', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=380,
  serialized_end=613,
)


_SPACEGATEWAYACCESSRESPONSE = _descriptor.Descriptor(
  name='SpaceGatewayAccessResponse',
  full_name='elint.services.product.identity.SpaceGatewayAccessResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='account_space_gateway_session_token_details', full_name='elint.services.product.identity.SpaceGatewayAccessResponse.account_space_gateway_session_token_details', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=616,
  serialized_end=770,
)

_ACCOUNTSPACEGATEWAYSESSIONTOKENDETAILS.fields_by_name['space_kind'].enum_type = _SPACEKIND
_ACCOUNTSPACEGATEWAYSESSIONTOKENDETAILS.fields_by_name['space_gateway_session_token_details'].message_type = ethos_dot_elint_dot_entities_dot_generic__pb2._PERSISTENTSESSIONTOKENDETAILS
_SPACEGATEWAYACCESSREQUEST.fields_by_name['identity_access_session_token_details'].message_type = ethos_dot_elint_dot_entities_dot_generic__pb2._PERSISTENTSESSIONTOKENDETAILS
_SPACEGATEWAYACCESSREQUEST.fields_by_name['space_kind'].enum_type = _SPACEKIND
_SPACEGATEWAYACCESSREQUEST.fields_by_name['requested_at'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_SPACEGATEWAYACCESSRESPONSE.fields_by_name['account_space_gateway_session_token_details'].message_type = _ACCOUNTSPACEGATEWAYSESSIONTOKENDETAILS
DESCRIPTOR.message_types_by_name['AccountSpaceGatewaySessionTokenDetails'] = _ACCOUNTSPACEGATEWAYSESSIONTOKENDETAILS
DESCRIPTOR.message_types_by_name['SpaceGatewayAccessRequest'] = _SPACEGATEWAYACCESSREQUEST
DESCRIPTOR.message_types_by_name['SpaceGatewayAccessResponse'] = _SPACEGATEWAYACCESSRESPONSE
DESCRIPTOR.enum_types_by_name['SpaceKind'] = _SPACEKIND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AccountSpaceGatewaySessionTokenDetails = _reflection.GeneratedProtocolMessageType('AccountSpaceGatewaySessionTokenDetails', (_message.Message,), {
  'DESCRIPTOR' : _ACCOUNTSPACEGATEWAYSESSIONTOKENDETAILS,
  '__module__' : 'ethos.elint.services.product.identity.account.space_gateway_account_pb2'
  # @@protoc_insertion_point(class_scope:elint.services.product.identity.AccountSpaceGatewaySessionTokenDetails)
  })
_sym_db.RegisterMessage(AccountSpaceGatewaySessionTokenDetails)

SpaceGatewayAccessRequest = _reflection.GeneratedProtocolMessageType('SpaceGatewayAccessRequest', (_message.Message,), {
  'DESCRIPTOR' : _SPACEGATEWAYACCESSREQUEST,
  '__module__' : 'ethos.elint.services.product.identity.account.space_gateway_account_pb2'
  # @@protoc_insertion_point(class_scope:elint.services.product.identity.SpaceGatewayAccessRequest)
  })
_sym_db.RegisterMessage(SpaceGatewayAccessRequest)

SpaceGatewayAccessResponse = _reflection.GeneratedProtocolMessageType('SpaceGatewayAccessResponse', (_message.Message,), {
  'DESCRIPTOR' : _SPACEGATEWAYACCESSRESPONSE,
  '__module__' : 'ethos.elint.services.product.identity.account.space_gateway_account_pb2'
  # @@protoc_insertion_point(class_scope:elint.services.product.identity.SpaceGatewayAccessResponse)
  })
_sym_db.RegisterMessage(SpaceGatewayAccessResponse)


DESCRIPTOR._options = None

_SPACEGATEWAYACCOUNTSERVICE = _descriptor.ServiceDescriptor(
  name='SpaceGatewayAccountService',
  full_name='elint.services.product.identity.SpaceGatewayAccountService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=838,
  serialized_end=1012,
  methods=[
  _descriptor.MethodDescriptor(
    name='SpaceGatewayAccess',
    full_name='elint.services.product.identity.SpaceGatewayAccountService.SpaceGatewayAccess',
    index=0,
    containing_service=None,
    input_type=_SPACEGATEWAYACCESSREQUEST,
    output_type=_SPACEGATEWAYACCESSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SPACEGATEWAYACCOUNTSERVICE)

DESCRIPTOR.services_by_name['SpaceGatewayAccountService'] = _SPACEGATEWAYACCOUNTSERVICE

# @@protoc_insertion_point(module_scope)
