# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from ethos.elint.services.product.identity.account import update_account_pb2 as ethos_dot_elint_dot_services_dot_product_dot_identity_dot_account_dot_update__account__pb2


class UpdateAccountServiceStub(object):
    """Service Definitions
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpdateAccountProfilePicture = channel.unary_unary(
                '/elint.services.product.identity.account.UpdateAccountService/UpdateAccountProfilePicture',
                request_serializer=ethos_dot_elint_dot_services_dot_product_dot_identity_dot_account_dot_update__account__pb2.UpdateAccountProfilePictureRequest.SerializeToString,
                response_deserializer=ethos_dot_elint_dot_services_dot_product_dot_identity_dot_account_dot_update__account__pb2.UpdateAccountProfilePictureResponse.FromString,
                )


class UpdateAccountServiceServicer(object):
    """Service Definitions
    """

    def UpdateAccountProfilePicture(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UpdateAccountServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpdateAccountProfilePicture': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateAccountProfilePicture,
                    request_deserializer=ethos_dot_elint_dot_services_dot_product_dot_identity_dot_account_dot_update__account__pb2.UpdateAccountProfilePictureRequest.FromString,
                    response_serializer=ethos_dot_elint_dot_services_dot_product_dot_identity_dot_account_dot_update__account__pb2.UpdateAccountProfilePictureResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'elint.services.product.identity.account.UpdateAccountService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class UpdateAccountService(object):
    """Service Definitions
    """

    @staticmethod
    def UpdateAccountProfilePicture(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/elint.services.product.identity.account.UpdateAccountService/UpdateAccountProfilePicture',
            ethos_dot_elint_dot_services_dot_product_dot_identity_dot_account_dot_update__account__pb2.UpdateAccountProfilePictureRequest.SerializeToString,
            ethos_dot_elint_dot_services_dot_product_dot_identity_dot_account_dot_update__account__pb2.UpdateAccountProfilePictureResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
