# -*- coding: utf-8 -*-

#   /*************************************************************************
#   *
#   * AMIT KUMAR KHETAN CONFIDENTIAL
#   * __________________
#   *
#   *  [2017] - [2021] Amit Kumar Khetan
#   *  All Rights Reserved.
#   *
#   * NOTICE:  All information contained herein is, and remains
#   * the property of Amit Kumar Khetan and its suppliers,
#   * if any.  The intellectual and technical concepts contained
#   * herein are proprietary to Amit Kumar Khetan
#   * and its suppliers and may be covered by U.S. and Foreign Patents,
#   * patents in process, and are protected by trade secret or copyright law.
#   * Dissemination of this information or reproduction of this material
#   * is strictly forbidden unless prior written permission is obtained
#   * from Amit Kumar Khetan.
#   */

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ethos/elint/services/product/identity/account/update_account.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ethos.elint.entities import account_pb2 as ethos_dot_elint_dot_entities_dot_account__pb2
try:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_account__pb2.google_dot_protobuf_dot_timestamp__pb2
except AttributeError:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_account__pb2.google.protobuf.timestamp_pb2
from ethos.elint.entities import generic_pb2 as ethos_dot_elint_dot_entities_dot_generic__pb2
try:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_generic__pb2.google_dot_protobuf_dot_timestamp__pb2
except AttributeError:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_generic__pb2.google.protobuf.timestamp_pb2
from ethos.elint.services.product.identity.account import access_account_pb2 as ethos_dot_elint_dot_services_dot_product_dot_identity_dot_account_dot_access__account__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ethos/elint/services/product/identity/account/update_account.proto',
  package='elint.services.product.identity.account',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\nBethos/elint/services/product/identity/account/update_account.proto\x12\'elint.services.product.identity.account\x1a\"ethos/elint/entities/account.proto\x1a\"ethos/elint/entities/generic.proto\x1a\x42\x65thos/elint/services/product/identity/account/access_account.proto\"\xa4\x01\n\"UpdateAccountProfilePictureRequest\x12\x66\n\x13\x61\x63\x63\x65ss_auth_details\x18\x01 \x01(\x0b\x32I.elint.services.product.identity.account.AccountServicesAccessAuthDetails\x12\x16\n\x0epicture_chunks\x18\x02 \x03(\x0c\"X\n#UpdateAccountProfilePictureResponse\x12\x31\n\rresponse_meta\x18\x01 \x01(\x0b\x32\x1a.elint.entity.ResponseMeta2\xd3\x01\n\x14UpdateAccountService\x12\xba\x01\n\x1bUpdateAccountProfilePicture\x12K.elint.services.product.identity.account.UpdateAccountProfilePictureRequest\x1aL.elint.services.product.identity.account.UpdateAccountProfilePictureResponse\"\x00\x62\x06proto3'
  ,
  dependencies=[ethos_dot_elint_dot_entities_dot_account__pb2.DESCRIPTOR,ethos_dot_elint_dot_entities_dot_generic__pb2.DESCRIPTOR,ethos_dot_elint_dot_services_dot_product_dot_identity_dot_account_dot_access__account__pb2.DESCRIPTOR,])




_UPDATEACCOUNTPROFILEPICTUREREQUEST = _descriptor.Descriptor(
  name='UpdateAccountProfilePictureRequest',
  full_name='elint.services.product.identity.account.UpdateAccountProfilePictureRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='access_auth_details', full_name='elint.services.product.identity.account.UpdateAccountProfilePictureRequest.access_auth_details', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='picture_chunks', full_name='elint.services.product.identity.account.UpdateAccountProfilePictureRequest.picture_chunks', index=1,
      number=2, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=252,
  serialized_end=416,
)


_UPDATEACCOUNTPROFILEPICTURERESPONSE = _descriptor.Descriptor(
  name='UpdateAccountProfilePictureResponse',
  full_name='elint.services.product.identity.account.UpdateAccountProfilePictureResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='response_meta', full_name='elint.services.product.identity.account.UpdateAccountProfilePictureResponse.response_meta', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=418,
  serialized_end=506,
)

_UPDATEACCOUNTPROFILEPICTUREREQUEST.fields_by_name['access_auth_details'].message_type = ethos_dot_elint_dot_services_dot_product_dot_identity_dot_account_dot_access__account__pb2._ACCOUNTSERVICESACCESSAUTHDETAILS
_UPDATEACCOUNTPROFILEPICTURERESPONSE.fields_by_name['response_meta'].message_type = ethos_dot_elint_dot_entities_dot_generic__pb2._RESPONSEMETA
DESCRIPTOR.message_types_by_name['UpdateAccountProfilePictureRequest'] = _UPDATEACCOUNTPROFILEPICTUREREQUEST
DESCRIPTOR.message_types_by_name['UpdateAccountProfilePictureResponse'] = _UPDATEACCOUNTPROFILEPICTURERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UpdateAccountProfilePictureRequest = _reflection.GeneratedProtocolMessageType('UpdateAccountProfilePictureRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEACCOUNTPROFILEPICTUREREQUEST,
  '__module__' : 'ethos.elint.services.product.identity.account.update_account_pb2'
  # @@protoc_insertion_point(class_scope:elint.services.product.identity.account.UpdateAccountProfilePictureRequest)
  })
_sym_db.RegisterMessage(UpdateAccountProfilePictureRequest)

UpdateAccountProfilePictureResponse = _reflection.GeneratedProtocolMessageType('UpdateAccountProfilePictureResponse', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEACCOUNTPROFILEPICTURERESPONSE,
  '__module__' : 'ethos.elint.services.product.identity.account.update_account_pb2'
  # @@protoc_insertion_point(class_scope:elint.services.product.identity.account.UpdateAccountProfilePictureResponse)
  })
_sym_db.RegisterMessage(UpdateAccountProfilePictureResponse)



_UPDATEACCOUNTSERVICE = _descriptor.ServiceDescriptor(
  name='UpdateAccountService',
  full_name='elint.services.product.identity.account.UpdateAccountService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=509,
  serialized_end=720,
  methods=[
  _descriptor.MethodDescriptor(
    name='UpdateAccountProfilePicture',
    full_name='elint.services.product.identity.account.UpdateAccountService.UpdateAccountProfilePicture',
    index=0,
    containing_service=None,
    input_type=_UPDATEACCOUNTPROFILEPICTUREREQUEST,
    output_type=_UPDATEACCOUNTPROFILEPICTURERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_UPDATEACCOUNTSERVICE)

DESCRIPTOR.services_by_name['UpdateAccountService'] = _UPDATEACCOUNTSERVICE

# @@protoc_insertion_point(module_scope)
