# -*- coding: utf-8 -*-

#   /*************************************************************************
#   *
#   * AMIT KUMAR KHETAN CONFIDENTIAL
#   * __________________
#   *
#   *  [2017] - [2021] Amit Kumar Khetan
#   *  All Rights Reserved.
#   *
#   * NOTICE:  All information contained herein is, and remains
#   * the property of Amit Kumar Khetan and its suppliers,
#   * if any.  The intellectual and technical concepts contained
#   * herein are proprietary to Amit Kumar Khetan
#   * and its suppliers and may be covered by U.S. and Foreign Patents,
#   * patents in process, and are protected by trade secret or copyright law.
#   * Dissemination of this information or reproduction of this material
#   * is strictly forbidden unless prior written permission is obtained
#   * from Amit Kumar Khetan.
#   */

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ethos/elint/entities/machine.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ethos/elint/entities/machine.proto',
  package='elint.entity',
  syntax='proto3',
  serialized_options=b'\n\014elint.entityB\014MachineProtoP\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\"ethos/elint/entities/machine.proto\x12\x0c\x65lint.entity\"\xfc\x02\n\x07Machine\x12\x12\n\nmachine_id\x18\x01 \x01(\t\x12:\n\x12machine_class_enum\x18\x02 \x01(\x0e\x32\x1e.elint.entity.MachineClassEnum\x12\x38\n\x11machine_name_enum\x18\x03 \x01(\x0e\x32\x1d.elint.entity.MachineNameEnum\x12\x38\n\x11machine_type_enum\x18\x04 \x01(\x0e\x32\x1d.elint.entity.MachineTypeEnum\x12\x15\n\rcan_be_shared\x18\x05 \x01(\x08\x12\x13\n\x0bhourly_rate\x18\x06 \x01(\x01\x12#\n\x1b\x62\x61seline_performance_factor\x18\x07 \x01(\x05\x12\x1e\n\x16\x62\x61seline_memory_factor\x18\x08 \x01(\x05\x12\x1f\n\x17\x62\x61seline_network_factor\x18\t \x01(\x05\x12\x1b\n\x13machine_description\x18\n \x01(\t*0\n\x10MachineClassEnum\x12\x0b\n\x07GENERAL\x10\x00\x12\x0f\n\x0b\x41\x43\x43\x45LERATED\x10\x01**\n\x0fMachineNameEnum\x12\x06\n\x02X2\x10\x00\x12\x07\n\x03M2N\x10\x01\x12\x06\n\x02M2\x10\x02*a\n\x0fMachineTypeEnum\x12\x08\n\x04NANO\x10\x00\x12\t\n\x05MICRO\x10\x01\x12\t\n\x05SMALL\x10\x02\x12\n\n\x06MEDIUM\x10\x03\x12\t\n\x05LARGE\x10\x04\x12\n\n\x06XLARGE\x10\x05\x12\x0b\n\x07XXLARGE\x10\x06\x42\x1e\n\x0c\x65lint.entityB\x0cMachineProtoP\x01\x62\x06proto3'
)

_MACHINECLASSENUM = _descriptor.EnumDescriptor(
  name='MachineClassEnum',
  full_name='elint.entity.MachineClassEnum',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='GENERAL', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ACCELERATED', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=435,
  serialized_end=483,
)
_sym_db.RegisterEnumDescriptor(_MACHINECLASSENUM)

MachineClassEnum = enum_type_wrapper.EnumTypeWrapper(_MACHINECLASSENUM)
_MACHINENAMEENUM = _descriptor.EnumDescriptor(
  name='MachineNameEnum',
  full_name='elint.entity.MachineNameEnum',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='X2', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='M2N', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='M2', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=485,
  serialized_end=527,
)
_sym_db.RegisterEnumDescriptor(_MACHINENAMEENUM)

MachineNameEnum = enum_type_wrapper.EnumTypeWrapper(_MACHINENAMEENUM)
_MACHINETYPEENUM = _descriptor.EnumDescriptor(
  name='MachineTypeEnum',
  full_name='elint.entity.MachineTypeEnum',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NANO', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MICRO', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SMALL', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MEDIUM', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='LARGE', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='XLARGE', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='XXLARGE', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=529,
  serialized_end=626,
)
_sym_db.RegisterEnumDescriptor(_MACHINETYPEENUM)

MachineTypeEnum = enum_type_wrapper.EnumTypeWrapper(_MACHINETYPEENUM)
GENERAL = 0
ACCELERATED = 1
X2 = 0
M2N = 1
M2 = 2
NANO = 0
MICRO = 1
SMALL = 2
MEDIUM = 3
LARGE = 4
XLARGE = 5
XXLARGE = 6



_MACHINE = _descriptor.Descriptor(
  name='Machine',
  full_name='elint.entity.Machine',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='machine_id', full_name='elint.entity.Machine.machine_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='machine_class_enum', full_name='elint.entity.Machine.machine_class_enum', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='machine_name_enum', full_name='elint.entity.Machine.machine_name_enum', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='machine_type_enum', full_name='elint.entity.Machine.machine_type_enum', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='can_be_shared', full_name='elint.entity.Machine.can_be_shared', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hourly_rate', full_name='elint.entity.Machine.hourly_rate', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='baseline_performance_factor', full_name='elint.entity.Machine.baseline_performance_factor', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='baseline_memory_factor', full_name='elint.entity.Machine.baseline_memory_factor', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='baseline_network_factor', full_name='elint.entity.Machine.baseline_network_factor', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='machine_description', full_name='elint.entity.Machine.machine_description', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=433,
)

_MACHINE.fields_by_name['machine_class_enum'].enum_type = _MACHINECLASSENUM
_MACHINE.fields_by_name['machine_name_enum'].enum_type = _MACHINENAMEENUM
_MACHINE.fields_by_name['machine_type_enum'].enum_type = _MACHINETYPEENUM
DESCRIPTOR.message_types_by_name['Machine'] = _MACHINE
DESCRIPTOR.enum_types_by_name['MachineClassEnum'] = _MACHINECLASSENUM
DESCRIPTOR.enum_types_by_name['MachineNameEnum'] = _MACHINENAMEENUM
DESCRIPTOR.enum_types_by_name['MachineTypeEnum'] = _MACHINETYPEENUM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Machine = _reflection.GeneratedProtocolMessageType('Machine', (_message.Message,), {
  'DESCRIPTOR' : _MACHINE,
  '__module__' : 'ethos.elint.entities.machine_pb2'
  # @@protoc_insertion_point(class_scope:elint.entity.Machine)
  })
_sym_db.RegisterMessage(Machine)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
