# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ethos/elint/entities/space.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ethos.elint.entities import account_pb2 as ethos_dot_elint_dot_entities_dot_account__pb2
try:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_account__pb2.google_dot_protobuf_dot_timestamp__pb2
except AttributeError:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_account__pb2.google.protobuf.timestamp_pb2
from ethos.elint.entities import galaxy_pb2 as ethos_dot_elint_dot_entities_dot_galaxy__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ethos/elint/entities/space.proto',
  package='elint.entity',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n ethos/elint/entities/space.proto\x12\x0c\x65lint.entity\x1a\"ethos/elint/entities/account.proto\x1a!ethos/elint/entities/galaxy.proto\"\xac\x01\n\x05Space\x12$\n\x06galaxy\x18\x01 \x01(\x0b\x32\x14.elint.entity.Galaxy\x12\x10\n\x08space_id\x18\x02 \x01(\t\x12+\n\nspace_type\x18\x03 \x01(\x0e\x32\x17.elint.entity.SpaceType\x12>\n\x14space_isolation_type\x18\x04 \x01(\x0e\x32 .elint.entity.SpaceIsolationType*!\n\tSpaceType\x12\n\n\x06\x43LOSED\x10\x00\x12\x08\n\x04OPEN\x10\x01*4\n\x12SpaceIsolationType\x12\x10\n\x0cNOT_ISOLATED\x10\x00\x12\x0c\n\x08ISOLATED\x10\x01\x62\x06proto3'
  ,
  dependencies=[ethos_dot_elint_dot_entities_dot_account__pb2.DESCRIPTOR,ethos_dot_elint_dot_entities_dot_galaxy__pb2.DESCRIPTOR,])

_SPACETYPE = _descriptor.EnumDescriptor(
  name='SpaceType',
  full_name='elint.entity.SpaceType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CLOSED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='OPEN', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=296,
  serialized_end=329,
)
_sym_db.RegisterEnumDescriptor(_SPACETYPE)

SpaceType = enum_type_wrapper.EnumTypeWrapper(_SPACETYPE)
_SPACEISOLATIONTYPE = _descriptor.EnumDescriptor(
  name='SpaceIsolationType',
  full_name='elint.entity.SpaceIsolationType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='NOT_ISOLATED', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ISOLATED', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=331,
  serialized_end=383,
)
_sym_db.RegisterEnumDescriptor(_SPACEISOLATIONTYPE)

SpaceIsolationType = enum_type_wrapper.EnumTypeWrapper(_SPACEISOLATIONTYPE)
CLOSED = 0
OPEN = 1
NOT_ISOLATED = 0
ISOLATED = 1



_SPACE = _descriptor.Descriptor(
  name='Space',
  full_name='elint.entity.Space',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='galaxy', full_name='elint.entity.Space.galaxy', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='space_id', full_name='elint.entity.Space.space_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='space_type', full_name='elint.entity.Space.space_type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='space_isolation_type', full_name='elint.entity.Space.space_isolation_type', index=3,
      number=4, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=122,
  serialized_end=294,
)

_SPACE.fields_by_name['galaxy'].message_type = ethos_dot_elint_dot_entities_dot_galaxy__pb2._GALAXY
_SPACE.fields_by_name['space_type'].enum_type = _SPACETYPE
_SPACE.fields_by_name['space_isolation_type'].enum_type = _SPACEISOLATIONTYPE
DESCRIPTOR.message_types_by_name['Space'] = _SPACE
DESCRIPTOR.enum_types_by_name['SpaceType'] = _SPACETYPE
DESCRIPTOR.enum_types_by_name['SpaceIsolationType'] = _SPACEISOLATIONTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Space = _reflection.GeneratedProtocolMessageType('Space', (_message.Message,), {
  'DESCRIPTOR' : _SPACE,
  '__module__' : 'ethos.elint.entities.space_pb2'
  # @@protoc_insertion_point(class_scope:elint.entity.Space)
  })
_sym_db.RegisterMessage(Space)


# @@protoc_insertion_point(module_scope)
