# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from ethos.elint.entities import generic_pb2 as ethos_dot_elint_dot_entities_dot_generic__pb2
from ethos.elint.services.product.knowledge.space_knowledge_domain_file import delete_space_knowledge_domain_file_pb2 as ethos_dot_elint_dot_services_dot_product_dot_knowledge_dot_space__knowledge__domain__file_dot_delete__space__knowledge__domain__file__pb2


class DeleteSpaceKnowledgeDomainFileServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DeleteSpaceKnowledgeDomainFile = channel.unary_unary(
                '/elint.services.product.knowledge.file.DeleteSpaceKnowledgeDomainFileService/DeleteSpaceKnowledgeDomainFile',
                request_serializer=ethos_dot_elint_dot_services_dot_product_dot_knowledge_dot_space__knowledge__domain__file_dot_delete__space__knowledge__domain__file__pb2.DeleteSpaceKnowledgeDomainFileRequest.SerializeToString,
                response_deserializer=ethos_dot_elint_dot_entities_dot_generic__pb2.ResponseMeta.FromString,
                )


class DeleteSpaceKnowledgeDomainFileServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DeleteSpaceKnowledgeDomainFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DeleteSpaceKnowledgeDomainFileServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DeleteSpaceKnowledgeDomainFile': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSpaceKnowledgeDomainFile,
                    request_deserializer=ethos_dot_elint_dot_services_dot_product_dot_knowledge_dot_space__knowledge__domain__file_dot_delete__space__knowledge__domain__file__pb2.DeleteSpaceKnowledgeDomainFileRequest.FromString,
                    response_serializer=ethos_dot_elint_dot_entities_dot_generic__pb2.ResponseMeta.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'elint.services.product.knowledge.file.DeleteSpaceKnowledgeDomainFileService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DeleteSpaceKnowledgeDomainFileService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DeleteSpaceKnowledgeDomainFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/elint.services.product.knowledge.file.DeleteSpaceKnowledgeDomainFileService/DeleteSpaceKnowledgeDomainFile',
            ethos_dot_elint_dot_services_dot_product_dot_knowledge_dot_space__knowledge__domain__file_dot_delete__space__knowledge__domain__file__pb2.DeleteSpaceKnowledgeDomainFileRequest.SerializeToString,
            ethos_dot_elint_dot_entities_dot_generic__pb2.ResponseMeta.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
