# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ethos/elint/services/product/identity/onboard_organization_space.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ethos.elint.entities import organization_space_pb2 as ethos_dot_elint_dot_entities_dot_organization__space__pb2
try:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_organization__space__pb2.google_dot_protobuf_dot_timestamp__pb2
except AttributeError:
  google_dot_protobuf_dot_timestamp__pb2 = ethos_dot_elint_dot_entities_dot_organization__space__pb2.google.protobuf.timestamp_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ethos/elint/services/product/identity/onboard_organization_space.proto',
  package='elint.services.product.identity',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\nFethos/elint/services/product/identity/onboard_organization_space.proto\x12\x1f\x65lint.services.product.identity\x1a-ethos/elint/entities/organization_space.proto2\x9a\x01\n\x1fOnboardOrganizationSpaceService\x12w\n\x18\x63laim_organization_space\x12+.elint.entity.ClaimOrganizationSpaceRequest\x1a,.elint.entity.ClaimOrganizationSpaceResponse\"\x00\x62\x06proto3'
  ,
  dependencies=[ethos_dot_elint_dot_entities_dot_organization__space__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_ONBOARDORGANIZATIONSPACESERVICE = _descriptor.ServiceDescriptor(
  name='OnboardOrganizationSpaceService',
  full_name='elint.services.product.identity.OnboardOrganizationSpaceService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=155,
  serialized_end=309,
  methods=[
  _descriptor.MethodDescriptor(
    name='claim_organization_space',
    full_name='elint.services.product.identity.OnboardOrganizationSpaceService.claim_organization_space',
    index=0,
    containing_service=None,
    input_type=ethos_dot_elint_dot_entities_dot_organization__space__pb2._CLAIMORGANIZATIONSPACEREQUEST,
    output_type=ethos_dot_elint_dot_entities_dot_organization__space__pb2._CLAIMORGANIZATIONSPACERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ONBOARDORGANIZATIONSPACESERVICE)

DESCRIPTOR.services_by_name['OnboardOrganizationSpaceService'] = _ONBOARDORGANIZATIONSPACESERVICE

# @@protoc_insertion_point(module_scope)
